USE [master]
GO

/****** Object:  Database [PPE20SQL]    Script Date: 25/04/2022 15:00:50 ******/
CREATE DATABASE [PPE20SQL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PPE20SQL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PPE20SQL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PPE20SQL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PPE20SQL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PPE20SQL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PPE20SQL] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PPE20SQL] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PPE20SQL] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PPE20SQL] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PPE20SQL] SET ARITHABORT OFF 
GO

ALTER DATABASE [PPE20SQL] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PPE20SQL] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PPE20SQL] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PPE20SQL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PPE20SQL] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PPE20SQL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PPE20SQL] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PPE20SQL] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PPE20SQL] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PPE20SQL] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PPE20SQL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PPE20SQL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PPE20SQL] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PPE20SQL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PPE20SQL] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PPE20SQL] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PPE20SQL] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PPE20SQL] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PPE20SQL] SET  MULTI_USER 
GO

ALTER DATABASE [PPE20SQL] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PPE20SQL] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PPE20SQL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PPE20SQL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PPE20SQL] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PPE20SQL] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PPE20SQL] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PPE20SQL] SET  READ_WRITE 
GO

